### ISSUE TITLE
Unkown Image Format

### ISSUE THREAD

**Issue by pops64** [Tweeticoats/stash-vr-companion#15]
I am not sure where I have an unkown image. It seems to crash when I ever I come across this and it doesn't specify what image it is calling that it is upset about. Another than number 1125 but who knows what that is. I will rerun a scan and generate to see if this remedies the problem.
```unknown image format
2023-11-10 00:33:45 fetching image: 1125
2023-11-10 00:33:45 Traceback (most recent call last):
2023-11-10 00:33:45   File "app.py", line 2327, in <module>
2023-11-10 00:33:45     refreshCache()
2023-11-10 00:33:45   File "app.py", line 1755, in refreshCache
2023-11-10 00:33:45     with Image.open(BytesIO(r.content)) as im:
2023-11-10 00:33:45   File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 3186, in open
2023-11-10 00:33:45     raise UnidentifiedImageError(
2023-11-10 00:33:45 PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f91311a74c0>```

**Comment by pops64** [comment]
I forgot I moved my data to another drive. The database still has the old drive path(Windows grr). Probably causing the above error.

**Comment by pops64** [comment]
I was able to compile the cache once when I restarted the server as new things were add I get this.  On the first compile of the cache I got a bunch of unknown formats but it handled it gracefully
```2023-11-10 03:03:24 Traceback (most recent call last):
2023-11-10 03:03:24   File "app.py", line 2327, in <module>
2023-11-10 03:03:24     refreshCache()
2023-11-10 03:03:24   File "app.py", line 1774, in refreshCache
2023-11-10 03:03:24     with Image.open(BytesIO(r.content)) as im:
2023-11-10 03:03:24   File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 3186, in open
2023-11-10 03:03:24     raise UnidentifiedImageError(
2023-11-10 03:03:24 PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fc410c7b100>
2023-11-10 03:03:24 unable to load app 0 (mountpoint='') (callable not found or import error)```
